---
title: "cleanup_project_ownership_table"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{cleanup_project_ownership_table}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, echo=FALSE}
library(rcc.billing)
library(DiagrammeR)
```

`cleanup_project_ownership_table.R` identifies projects with ownership issues, nominates a new owner if possible, and writes that owner to the project ownership data. It cannot always determine a new owner. It logs the changes it makes to ownership data and the projects where it cannot fix the ownership data.
```{r mermaid_diagram, echo=FALSE, fig.align='center'}
DiagrammeR::mermaid("
graph TD
    subgraph Suppliers
        S1[REDCap Database]
    end

    subgraph Inputs
        I1[redcap_entity_project_ownership]
        I2[redcap_user_information]
        I3[redcap_projects]
        I4[redcap_user_rights]
        I5[redcap_user_roles]
    end

    subgraph Process
        P1[Identify Projects with<br/>Ownership Issues]
        P2[Get Projects<br/>Needing New Owners]
        P3[Get Projects<br/>Without Owners]
        P4[Get Research Projects<br/>Not Using Viable PI Data]
        P5[Nominate<br/>New Owners]
        P6[Create owner<br/>updates dataset]
        P7[Create owner<br/>erasures dataset]
        P8[Combine owner updates<br/>and erasures]

        P1 --> P2
        P1 --> P3
        P1 --> P4
        P2 --> P5
        P3 --> P5
        P4 --> P5
        P5 --> P6
        P5 --> P7
        P6 --> P8
        P7 --> P8
    end

    subgraph Outputs
        O1[redcap_entity_project_ownership<br/>updates]
        O2[rcc_job_log]
    end

    subgraph Customers
        C1[REDCap Database]
        C2[RCC Billing System]
    end

    S1 --> I1
    S1 --> I2
    S1 --> I3
    S1 --> I4
    S1 --> I5

    I1 --> P1
    I2 --> P1
    I3 --> P1
    I4 --> P1
    I5 --> P1

    P8 --> O1
    P8 --> O2

    O1 --> C1
    O2 --> C2
", width = 700, height= 700)
```
