CREATE TABLE `redcap_projects` (
  `project_id` int(10) NOT NULL,
  `project_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `app_title` text COLLATE utf8mb4_unicode_ci,
  `status` int(1) NOT NULL DEFAULT '0',
  `creation_time` datetime DEFAULT NULL,
  `production_time` datetime DEFAULT NULL,
  `inactive_time` datetime DEFAULT NULL,
  `completed_time` datetime DEFAULT NULL,
  `completed_by` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `data_locked` tinyint(1) NOT NULL DEFAULT '0',
  `log_event_table` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'redcap_log_event' COMMENT 'Project redcap_log_event table',
  `created_by` int(10) DEFAULT NULL COMMENT 'FK from User Info',
  `draft_mode` int(1) NOT NULL DEFAULT '0',
  `surveys_enabled` int(1) NOT NULL DEFAULT '0' COMMENT '0 = forms only, 1 = survey+forms, 2 = single survey only',
  `repeatforms` int(1) NOT NULL DEFAULT '0',
  `scheduling` int(1) NOT NULL DEFAULT '0',
  `purpose` int(2) DEFAULT NULL,
  `purpose_other` text COLLATE utf8mb4_unicode_ci,
  `show_which_records` int(1) NOT NULL DEFAULT '0',
  `__SALT__` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Alphanumeric hash unique to each project',
  `count_project` int(1) NOT NULL DEFAULT '1',
  `investigators` text COLLATE utf8mb4_unicode_ci,
  `project_note` mediumtext COLLATE utf8mb4_unicode_ci,
  `online_offline` int(1) NOT NULL DEFAULT '1',
  `auth_meth` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `double_data_entry` int(1) NOT NULL DEFAULT '0',
  `project_language` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'English',
  `project_encoding` enum('japanese_sjis','chinese_utf8','chinese_utf8_traditional') COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Encoding to be used for various exported files',
  `is_child_of` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `date_shift_max` int(10) NOT NULL DEFAULT '364',
  `institution` text COLLATE utf8mb4_unicode_ci,
  `site_org_type` text COLLATE utf8mb4_unicode_ci,
  `grant_cite` text COLLATE utf8mb4_unicode_ci,
  `project_contact_name` text COLLATE utf8mb4_unicode_ci,
  `project_contact_email` text COLLATE utf8mb4_unicode_ci,
  `headerlogo` text COLLATE utf8mb4_unicode_ci,
  `auto_inc_set` int(1) NOT NULL DEFAULT '0',
  `custom_data_entry_note` text COLLATE utf8mb4_unicode_ci,
  `custom_index_page_note` text COLLATE utf8mb4_unicode_ci,
  `order_id_by` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `custom_reports` mediumtext COLLATE utf8mb4_unicode_ci COMMENT 'Legacy report builder',
  `report_builder` mediumtext COLLATE utf8mb4_unicode_ci,
  `disable_data_entry` int(1) NOT NULL DEFAULT '0',
  `google_translate_default` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `require_change_reason` int(1) NOT NULL DEFAULT '0',
  `dts_enabled` int(1) NOT NULL DEFAULT '0',
  `project_pi_firstname` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `project_pi_mi` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `project_pi_lastname` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `project_pi_email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `project_pi_alias` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `project_pi_username` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `project_pi_pub_exclude` int(1) DEFAULT NULL,
  `project_pub_matching_institution` text COLLATE utf8mb4_unicode_ci,
  `project_irb_number` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `project_grant_number` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `history_widget_enabled` int(1) NOT NULL DEFAULT '1',
  `secondary_pk` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'field_name of seconary identifier',
  `secondary_pk_display_value` tinyint(1) NOT NULL DEFAULT '1',
  `secondary_pk_display_label` tinyint(1) NOT NULL DEFAULT '1',
  `custom_record_label` text COLLATE utf8mb4_unicode_ci,
  `display_project_logo_institution` int(1) NOT NULL DEFAULT '1',
  `imported_from_rs` int(1) NOT NULL DEFAULT '0' COMMENT 'If imported from REDCap Survey',
  `display_today_now_button` int(1) NOT NULL DEFAULT '1',
  `auto_variable_naming` int(1) NOT NULL DEFAULT '0',
  `randomization` int(1) NOT NULL DEFAULT '0',
  `enable_participant_identifiers` int(1) NOT NULL DEFAULT '0',
  `survey_email_participant_field` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Field name that stores participant email',
  `survey_phone_participant_field` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Field name that stores participant phone number',
  `data_entry_trigger_url` text COLLATE utf8mb4_unicode_ci COMMENT 'URL for sending Post request when a record is created or modified',
  `template_id` int(10) DEFAULT NULL COMMENT 'If created from a project template, the project_id of the template',
  `date_deleted` datetime DEFAULT NULL COMMENT 'Time that project was flagged for deletion',
  `data_resolution_enabled` int(1) NOT NULL DEFAULT '1' COMMENT '0=Disabled, 1=Field comment log, 2=Data Quality resolution workflow',
  `field_comment_edit_delete` int(1) NOT NULL DEFAULT '1' COMMENT 'Allow users to edit or delete Field Comments',
  `realtime_webservice_enabled` int(1) NOT NULL DEFAULT '0' COMMENT 'Is real-time web service enabled for external data import?',
  `realtime_webservice_type` enum('CUSTOM','FHIR') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'CUSTOM',
  `realtime_webservice_offset_days` float NOT NULL DEFAULT '7' COMMENT 'Default value of days offset',
  `realtime_webservice_offset_plusminus` enum('+','-','+-') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '+-' COMMENT 'Default value of plus-minus range for days offset',
  `last_logged_event` datetime DEFAULT NULL,
  `edoc_upload_max` int(10) DEFAULT NULL,
  `file_attachment_upload_max` int(10) DEFAULT NULL,
  `survey_queue_custom_text` text COLLATE utf8mb4_unicode_ci,
  `survey_queue_hide` tinyint(1) NOT NULL DEFAULT '0',
  `survey_auth_enabled` int(1) NOT NULL DEFAULT '0',
  `survey_auth_field1` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `survey_auth_event_id1` int(10) DEFAULT NULL,
  `survey_auth_field2` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `survey_auth_event_id2` int(10) DEFAULT NULL,
  `survey_auth_field3` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `survey_auth_event_id3` int(10) DEFAULT NULL,
  `survey_auth_min_fields` enum('1','2','3') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `survey_auth_apply_all_surveys` int(1) NOT NULL DEFAULT '1',
  `survey_auth_custom_message` text COLLATE utf8mb4_unicode_ci,
  `survey_auth_fail_limit` int(2) DEFAULT NULL,
  `survey_auth_fail_window` int(3) DEFAULT NULL,
  `twilio_enabled` int(1) NOT NULL DEFAULT '0',
  `twilio_modules_enabled` enum('SURVEYS','ALERTS','SURVEYS_ALERTS') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'SURVEYS',
  `twilio_hide_in_project` tinyint(1) NOT NULL DEFAULT '0',
  `twilio_account_sid` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `twilio_auth_token` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `twilio_from_number` bigint(16) DEFAULT NULL,
  `twilio_voice_language` varchar(5) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'en',
  `twilio_option_voice_initiate` tinyint(1) NOT NULL DEFAULT '0',
  `twilio_option_sms_initiate` tinyint(1) NOT NULL DEFAULT '0',
  `twilio_option_sms_invite_make_call` tinyint(1) NOT NULL DEFAULT '0',
  `twilio_option_sms_invite_receive_call` tinyint(1) NOT NULL DEFAULT '0',
  `twilio_option_sms_invite_web` tinyint(1) NOT NULL DEFAULT '0',
  `twilio_default_delivery_preference` enum('EMAIL','VOICE_INITIATE','SMS_INITIATE','SMS_INVITE_MAKE_CALL','SMS_INVITE_RECEIVE_CALL','SMS_INVITE_WEB') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'EMAIL',
  `twilio_request_inspector_checked` datetime DEFAULT NULL,
  `twilio_request_inspector_enabled` int(1) NOT NULL DEFAULT '1',
  `twilio_append_response_instructions` int(1) NOT NULL DEFAULT '1',
  `twilio_multiple_sms_behavior` enum('OVERWRITE','CHOICE','FIRST') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'CHOICE',
  `twilio_delivery_preference_field_map` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `two_factor_exempt_project` tinyint(1) NOT NULL DEFAULT '0',
  `two_factor_force_project` tinyint(1) NOT NULL DEFAULT '0',
  `disable_autocalcs` tinyint(1) NOT NULL DEFAULT '0',
  `custom_public_survey_links` text COLLATE utf8mb4_unicode_ci,
  `pdf_custom_header_text` text COLLATE utf8mb4_unicode_ci,
  `pdf_show_logo_url` tinyint(1) NOT NULL DEFAULT '1',
  `pdf_hide_secondary_field` tinyint(1) NOT NULL DEFAULT '0',
  `pdf_hide_record_id` tinyint(1) NOT NULL DEFAULT '0',
  `shared_library_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `allow_delete_record_from_log` tinyint(1) NOT NULL DEFAULT '0',
  `delete_file_repository_export_files` int(3) NOT NULL DEFAULT '0' COMMENT 'Will auto-delete files after X days',
  `custom_project_footer_text` text COLLATE utf8mb4_unicode_ci,
  `custom_project_footer_text_link` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `google_recaptcha_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `datamart_allow_repeat_revision` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'If true, a normal user can run a revision multiple times',
  `datamart_allow_create_revision` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'If true, a normal user can request a new revision',
  `datamart_enabled` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Is project a Clinical Data Mart project?',
  `break_the_glass_enabled` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Are users allowed to use the Epic feature Break-the-Glass feature?',
  `datamart_cron_enabled` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'If true, the cron job will pull data automatically for all records at a specified interval X times per day.',
  `datamart_cron_end_date` datetime DEFAULT NULL COMMENT 'stop processing the cron job after this date',
  `fhir_include_email_address_project` tinyint(1) DEFAULT NULL,
  `file_upload_vault_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `file_upload_versioning_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `missing_data_codes` text COLLATE utf8mb4_unicode_ci,
  `record_locking_pdf_vault_enabled` tinyint(1) NOT NULL DEFAULT '0',
  `record_locking_pdf_vault_custom_text` text COLLATE utf8mb4_unicode_ci,
  `fhir_cdp_auto_adjudication_enabled` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'If true, auto adjudicate data in CDP projects',
  `fhir_cdp_auto_adjudication_cronjob_enabled` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'If true, the cron job will auto adjudicate data in CDP projects',
  `project_dashboard_min_data_points` int(10) DEFAULT NULL,
  `bypass_branching_erase_field_prompt` tinyint(1) NOT NULL DEFAULT '0',
  `protected_email_mode` tinyint(1) NOT NULL DEFAULT '0',
  `protected_email_mode_custom_text` text COLLATE utf8mb4_unicode_ci,
  `protected_email_mode_trigger` enum('ALL','PIPING') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ALL',
  `protected_email_mode_logo` int(10) DEFAULT NULL,
  `hide_filled_forms` tinyint(1) NOT NULL DEFAULT '1',
  `form_activation_survey_autocontinue` tinyint(1) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Stores project-level values';


ALTER TABLE `redcap_projects`
  ADD PRIMARY KEY (`project_id`),
  ADD UNIQUE KEY `project_name` (`project_name`),
  ADD UNIQUE KEY `twilio_from_number` (`twilio_from_number`),
  ADD KEY `app_title` (`app_title`(190)),
  ADD KEY `auth_meth` (`auth_meth`),
  ADD KEY `completed_by` (`completed_by`),
  ADD KEY `completed_time` (`completed_time`),
  ADD KEY `created_by` (`created_by`),
  ADD KEY `date_deleted` (`date_deleted`),
  ADD KEY `delete_file_repository_export_files` (`delete_file_repository_export_files`),
  ADD KEY `last_logged_event` (`last_logged_event`),
  ADD KEY `project_note` (`project_note`(190)),
  ADD KEY `protected_email_mode_logo` (`protected_email_mode_logo`),
  ADD KEY `survey_auth_event_id1` (`survey_auth_event_id1`),
  ADD KEY `survey_auth_event_id2` (`survey_auth_event_id2`),
  ADD KEY `survey_auth_event_id3` (`survey_auth_event_id3`),
  ADD KEY `template_id` (`template_id`),
  ADD KEY `twilio_account_sid` (`twilio_account_sid`);


ALTER TABLE `redcap_projects`
  MODIFY `project_id` int(10) NOT NULL AUTO_INCREMENT;


ALTER TABLE `redcap_projects`
  ADD CONSTRAINT `redcap_projects_ibfk_1` FOREIGN KEY (`created_by`) REFERENCES `redcap_user_information` (`ui_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `redcap_projects_ibfk_2` FOREIGN KEY (`protected_email_mode_logo`) REFERENCES `redcap_edocs_metadata` (`doc_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `redcap_projects_ibfk_3` FOREIGN KEY (`survey_auth_event_id1`) REFERENCES `redcap_events_metadata` (`event_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `redcap_projects_ibfk_4` FOREIGN KEY (`survey_auth_event_id2`) REFERENCES `redcap_events_metadata` (`event_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `redcap_projects_ibfk_5` FOREIGN KEY (`survey_auth_event_id3`) REFERENCES `redcap_events_metadata` (`event_id`) ON DELETE SET NULL ON UPDATE CASCADE,
  ADD CONSTRAINT `redcap_projects_ibfk_6` FOREIGN KEY (`template_id`) REFERENCES `redcap_projects` (`project_id`) ON DELETE SET NULL ON UPDATE CASCADE;
