CREATE TABLE `redcap_log_event` (
  `log_event_id` int(11) NOT NULL AUTO_INCREMENT,
  `project_id` int(10) NOT NULL DEFAULT '0',
  `ts` bigint(14) DEFAULT NULL,
  `user` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ip` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `page` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `event` enum('UPDATE','INSERT','DELETE','SELECT','ERROR','LOGIN','LOGOUT','OTHER','DATA_EXPORT','DOC_UPLOAD','DOC_DELETE','MANAGE','LOCK_RECORD','ESIGNATURE') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `object_type` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `sql_log` mediumtext COLLATE utf8mb4_unicode_ci,
  `pk` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `event_id` int(10) DEFAULT NULL,
  `data_values` text COLLATE utf8mb4_unicode_ci,
  `description` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `legacy` int(1) NOT NULL DEFAULT '0',
  `change_reason` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`log_event_id`),
  KEY `description` (`description`),
  KEY `event_project` (`event`,`project_id`),
  KEY `object_type` (`object_type`),
  KEY `pk` (`pk`(191)),
  KEY `ts` (`ts`),
  KEY `user` (`user`(191)),
  KEY `user_project` (`project_id`,`user`(191))
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
