CREATE TABLE `redcap_user_information` (
  `ui_id` int(10) NOT NULL AUTO_INCREMENT,
  `username` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Primary email',
  `user_email2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Secondary email',
  `user_email3` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Tertiary email',
  `user_phone` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_phone_sms` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_firstname` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_lastname` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_inst_id` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `super_user` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Can access all projects and their data',
  `account_manager` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Can manage user accounts',
  `access_system_config` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Can access system configuration pages',
  `access_system_upgrade` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Can perform system upgrade',
  `access_external_module_install` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Can install, upgrade, and configure external modules',
  `admin_rights` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Can set administrator privileges',
  `access_admin_dashboards` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Can access admin dashboards',
  `user_creation` datetime DEFAULT NULL COMMENT 'Time user account was created',
  `user_firstvisit` datetime DEFAULT NULL,
  `user_firstactivity` datetime DEFAULT NULL,
  `user_lastactivity` datetime DEFAULT NULL,
  `user_lastlogin` datetime DEFAULT NULL,
  `user_suspended_time` datetime DEFAULT NULL,
  `user_expiration` datetime DEFAULT NULL COMMENT 'Time at which the user will be automatically suspended from REDCap',
  `user_access_dashboard_view` datetime DEFAULT NULL,
  `user_access_dashboard_email_queued` enum('QUEUED','SENDING') COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Tracks status of email reminder for User Access Dashboard',
  `user_sponsor` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Username of user''s sponsor or contact person',
  `user_comments` text COLLATE utf8mb4_unicode_ci COMMENT 'Miscellaneous comments about user',
  `allow_create_db` int(1) NOT NULL DEFAULT '1',
  `email_verify_code` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Primary email verification code',
  `email2_verify_code` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Secondary email verification code',
  `email3_verify_code` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'Tertiary email verification code',
  `datetime_format` enum('M-D-Y_24','M-D-Y_12','M/D/Y_24','M/D/Y_12','M.D.Y_24','M.D.Y_12','D-M-Y_24','D-M-Y_12','D/M/Y_24','D/M/Y_12','D.M.Y_24','D.M.Y_12','Y-M-D_24','Y-M-D_12','Y/M/D_24','Y/M/D_12','Y.M.D_24','Y.M.D_12') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'M/D/Y_12' COMMENT 'User''s preferred datetime viewing format',
  `number_format_decimal` enum('.',',') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '.' COMMENT 'User''s preferred decimal format',
  `number_format_thousands_sep` enum(',','.','','SPACE','''') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT ',' COMMENT 'User''s preferred thousands separator',
  `csv_delimiter` enum(',',';','TAB','SPACE','|','^') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT ',',
  `two_factor_auth_secret` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `display_on_email_users` int(1) NOT NULL DEFAULT '1',
  `two_factor_auth_twilio_prompt_phone` tinyint(1) NOT NULL DEFAULT '1',
  `two_factor_auth_code_expiration` int(3) NOT NULL DEFAULT '2',
  `api_token` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `messaging_email_preference` enum('NONE','2_HOURS','4_HOURS','6_HOURS','8_HOURS','12_HOURS','DAILY') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '4_HOURS',
  `messaging_email_urgent_all` tinyint(1) NOT NULL DEFAULT '1',
  `messaging_email_ts` datetime DEFAULT NULL,
  `messaging_email_general_system` tinyint(1) NOT NULL DEFAULT '1',
  `messaging_email_queue_time` datetime DEFAULT NULL,
  `ui_state` mediumtext COLLATE utf8mb4_unicode_ci,
  `api_token_auto_request` tinyint(1) NOT NULL DEFAULT '0',
  `fhir_data_mart_create_project` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ui_id`),
  UNIQUE KEY `api_token` (`api_token`),
  UNIQUE KEY `email2_verify_code` (`email2_verify_code`),
  UNIQUE KEY `email3_verify_code` (`email3_verify_code`),
  UNIQUE KEY `email_verify_code` (`email_verify_code`),
  UNIQUE KEY `username` (`username`),
  KEY `messaging_email_queue_time` (`messaging_email_queue_time`),
  KEY `two_factor_auth_secret` (`two_factor_auth_secret`),
  KEY `user_access_dashboard_email_queued` (`user_access_dashboard_email_queued`),
  KEY `user_access_dashboard_view` (`user_access_dashboard_view`),
  KEY `user_comments` (`user_comments`(190)),
  KEY `user_creation` (`user_creation`),
  KEY `user_email` (`user_email`(191)),
  KEY `user_expiration` (`user_expiration`),
  KEY `user_firstactivity` (`user_firstactivity`),
  KEY `user_firstname` (`user_firstname`(191)),
  KEY `user_firstvisit` (`user_firstvisit`),
  KEY `user_inst_id` (`user_inst_id`(191)),
  KEY `user_lastactivity` (`user_lastactivity`),
  KEY `user_lastlogin` (`user_lastlogin`),
  KEY `user_lastname` (`user_lastname`(191)),
  KEY `user_sponsor` (`user_sponsor`(191)),
  KEY `user_suspended_time` (`user_suspended_time`)
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
